### PR TITLE
Add prettier per latest addon blueprint

### PR DESCRIPTION
**Pull request by SergeAstapov**

### CODE REVIEW

**Comment by chriskrycho** [comment]
As with #50, mind updating this? 🙏🏼

**Comment by SergeAstapov** [comment]
> As with #50, mind updating this? 🙏🏼

done!

**Comment by chriskrycho** [comment]
Gah, I was afraid of this. Will need updating again now that #50 landed.

**Comment by SergeAstapov** [comment]
@chriskrycho done!

**Pull request merged**
